version: '2'
services:
  shardone:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "28001:27100"
    command: -c 'mongod --port 27100'
  shardtwo:
      build:
        context: .
        dockerfile: Dockerfile-db
      ports:
        - "28002:27100"
      command: -c 'mongod --port 27100'
  configserver:
      build:
        context: .
        dockerfile: Dockerfile-db
      ports:
        - "28003:27100"
      command: -c 'mongod --configsvr --port 27100'
      depends_on:
          - shardone
          - shardtwo
  mongoserver:
      build:
        context: .
        dockerfile: Dockerfile-db
      ports:
        - "28005:27100"
      command: -c 'mongos --configdb configserver:27100 --port 27100'
      depends_on:
        - configserver
  mongoserverconfigurer:
      build:
        context: .
        dockerfile: Dockerfile-configurer
      command: -c 'sleep 2; mongo mongodb://mongoserver:27100/ < tuning.js'
      depends_on:
        - mongoserver
  postgresql:
      image: postgres
      environment:
        - POSTGRES_DB=tmp
        - POSTGRES_PASSWORD=qwerty
      ports:
        - "5555:5432"
  # web:
  #     image: niaquinto/gradle
  #     volumes:
  #       - ./:/usr/bin/app:rw
  #     ports:
  #       - "8080:8080"
  #     environment:
  #       - DB_URL=jdbc:postgresql://postgresql/tmp
  #       - DB_USERNAME=postgres
  #       - DB_PASSWORD=qwerty
  #       - MONGO_URL=mongodb://mongoserver:27000
  #       - MONGO_PORT=27000
  #     command: bootRun
  #     container_name: testenv 
  #     depends_on:
  #       - postgresql
  #       - mongoserverconfigurer
  #       - mongoserver